basePath: /
definitions:
  helpers.SummAmount:
    properties:
      amount:
        type: number
    type: object
  models.Account:
    properties:
      balance:
        type: number
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Igor Zykunov
  description: REST API
  title: utm api
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: Создание аккаунта.
      parameters:
      - description: account add
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Account'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Account'
      summary: AddAccount
      tags:
      - Account
  /accounts/{id}/balance:
    get:
      consumes:
      - application/json
      description: Получение баланса
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: GetBalance
      tags:
      - Account
  /accounts/{id}/deposit:
    post:
      consumes:
      - application/json
      description: Внесение денег
      parameters:
      - description: deposit
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/helpers.SummAmount'
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Account'
      summary: Deposit
      tags:
      - Account
  /accounts/{id}/withdraw:
    post:
      consumes:
      - application/json
      description: Снятие денег
      parameters:
      - description: account add
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/helpers.SummAmount'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Account'
      summary: Withdrow
      tags:
      - Account
swagger: "2.0"
