basePath: /
definitions:
  helpers.AccountAdd:
    properties:
      balance:
        type: number
      name:
        type: string
      surname:
        type: string
    type: object
  helpers.AccountSuccess:
    properties:
      balance:
        default: 500.4
        type: number
      id:
        default: 1
        type: integer
      name:
        default: John
        type: string
      surname:
        default: Doe
        type: string
    type: object
  helpers.BalanceFail:
    properties:
      data:
        default: "0"
        type: string
      meta:
        default: "null"
        type: string
      status_code:
        default: 404
        type: integer
    type: object
  helpers.BalanceSuccess:
    properties:
      data:
        default: "400.54"
        type: string
      meta:
        default: "null"
        type: string
      status_code:
        default: 200
        type: integer
    type: object
  helpers.SummAmount:
    properties:
      amount:
        type: number
    type: object
  models.Account:
    properties:
      balance:
        type: number
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Igor Zykunov
  description: REST API
  title: utm api
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: Создание аккаунта.
      parameters:
      - description: account add
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/helpers.AccountAdd'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.AccountSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Account'
      summary: AddAccount
      tags:
      - Account
  /accounts/{id}/balance:
    get:
      consumes:
      - application/json
      description: Получение баланса
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.BalanceSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.BalanceFail'
      summary: GetBalance
      tags:
      - Account
  /accounts/{id}/deposit:
    post:
      consumes:
      - application/json
      description: Внесение денег
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: deposit
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/helpers.SummAmount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.AccountSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Account'
      summary: Deposit
      tags:
      - Account
  /accounts/{id}/withdraw:
    post:
      consumes:
      - application/json
      description: Снятие денег
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: withdraw
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/helpers.SummAmount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.AccountSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Account'
      summary: Withdrow
      tags:
      - Account
swagger: "2.0"
